/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UniEnumEditorTests
{
    public enum LayerId
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 2,

        /// <summary>
        /// Water
        /// </summary>
        Water = 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 5,

        /// <summary>
        /// アイウエオ
        /// </summary>
        アイウエオ = 17,

        /// <summary>
        /// !@#$%^&*()[]'/123 abcWXZ-11
        /// </summary>
        _123abcWXZ11 = 21,

    }

    [System.Flags]
    public enum LayerMaskValue
    {
        /// <summary>
        /// Default
        /// </summary>
        Default = 1 << 0,

        /// <summary>
        /// TransparentFX
        /// </summary>
        TransparentFX = 1 << 1,

        /// <summary>
        /// Ignore Raycast
        /// </summary>
        IgnoreRaycast = 1 << 2,

        /// <summary>
        /// Water
        /// </summary>
        Water = 1 << 4,

        /// <summary>
        /// UI
        /// </summary>
        UI = 1 << 5,

        /// <summary>
        /// アイウエオ
        /// </summary>
        アイウエオ = 1 << 17,

        /// <summary>
        /// !@#$%^&*()[]'/123 abcWXZ-11
        /// </summary>
        _123abcWXZ11 = 1 << 21,

    }

}

