/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UniEnumEditorTests
{
    public class SceneId
    {
        /// <summary>
        /// <para>0: UniEnumTest_100</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_100.unity
        /// </summary>
        public const int UniEnumTest_100 = 0;

        /// <summary>
        /// <para>1: UniEnumTest_101</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_101.unity
        /// </summary>
        public const int UniEnumTest_101 = 1;

        /// <summary>
        /// <para>2: UniEnumTest_102</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_102.unity
        /// </summary>
        public const int UniEnumTest_102 = 2;

    }

    public class SceneName
    {
        /// <summary>
        /// <para>0: UniEnumTest_100</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_100.unity
        /// </summary>
        public const string UniEnumTest_100 = "UniEnumTest_100";

        /// <summary>
        /// <para>1: UniEnumTest_101</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_101.unity
        /// </summary>
        public const string UniEnumTest_101 = "UniEnumTest_101";

        /// <summary>
        /// <para>2: UniEnumTest_102</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_102.unity
        /// </summary>
        public const string UniEnumTest_102 = "UniEnumTest_102";

    }

    public class ScenePath
    {
        /// <summary>
        /// <para>0: UniEnumTest_100</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_100.unity
        /// </summary>
        public const string UniEnumTest_100 = "Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_100.unity";

        /// <summary>
        /// <para>1: UniEnumTest_101</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_101.unity
        /// </summary>
        public const string UniEnumTest_101 = "Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_101.unity";

        /// <summary>
        /// <para>2: UniEnumTest_102</para>
        /// Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_102.unity
        /// </summary>
        public const string UniEnumTest_102 = "Assets/UniEnum.Tests/Editor/Scenes/UniEnumTest_102.unity";

    }

}

