/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>
using UnityEngine;

namespace UniEnumEditorTests
{
    public class SortingLayerId
    {
        public static readonly int Default = SortingLayer.NameToID("Default");

    }

    public class SortingLayerName
    {
        public const string Default = "Default";

    }

}

