/// <auto-generated>
/// This file is auto-generated by UniEnum.
/// </auto-generated>

namespace UniEnumEditorTests
{
    public class TagName
    {
        /// <summary>
        /// Untagged
        /// </summary>
        public static readonly string Untagged = "Untagged";

        /// <summary>
        /// Respawn
        /// </summary>
        public static readonly string Respawn = "Respawn";

        /// <summary>
        /// Finish
        /// </summary>
        public static readonly string Finish = "Finish";

        /// <summary>
        /// EditorOnly
        /// </summary>
        public static readonly string EditorOnly = "EditorOnly";

        /// <summary>
        /// MainCamera
        /// </summary>
        public static readonly string MainCamera = "MainCamera";

        /// <summary>
        /// Player
        /// </summary>
        public static readonly string Player = "Player";

        /// <summary>
        /// GameController
        /// </summary>
        public static readonly string GameController = "GameController";

        /// <summary>
        /// 12@hoge -##A
        /// </summary>
        public static readonly string _12hogeA = "12@hoge -##A";

    }

}

